var leds = [
     {
          id: 13,
          state: false,
          name: "Built In",
          info: "Denna LED sitter direkt på Arduinon",
          disabled: false,
     },
     {
          id: 3,
          state: false,
          name: "Grön",
          info: "Denna LED är grön och styrs via transistor",
          disabled: false,
     },
     {
          id: 2,
          state: false,
          name: "CW LED",
          info: "Denna LED är kall vit och styrs via transistor",
          disabled: false,
     },
     {
          id: 4,
          state: false,
          name: "Lokstallarna",
          info: "Lokstallarna",
          disabled: false,
     },
     {
          id: 5,
          state: false,
          name: "Bostäder_och_Butiker",
          info: "Bostäder och butiker",
          disabled: false,
     },
     {
          id: 6,
          state: false,
          name: "Skeppsbrokajen",
          info: "Skeppsbrokajen eller “Skeppsbrokajen” är för nuläget ganska tom där inte många byggnader följer kanten. De få byggnader som finns används som konferens byggnader eller restauranger, detta är perfekt och vill ha fler. Skeppsbrokajen ska också ha en gångbana längs med små platser där folk kan samlas för aktiviteter.",
          disabled: false,
          picture: "https://www.nordicchoicehotels.se/globalassets/global/hotel-pictures/clarion-hotel/clarion-collection-hotel-carlscrona/the-hotel/surrounding-exterior-clarion-collection-hotel-carlscrona.jpg",
          hasPage: true,
     },
     {
          id: 7,
          state: false,
          name: "Hotell",
          info: "Hotell",
          disabled: false,
     },
     {
          id: 8,
          state: false,
          name: "Park",
          info: "Park",
          disabled: false,
     },
     {
          id: 9,
          state: false,
          name: "Simhall",
          info: "Karlskrona Simhall",
          disabled: false,
     },
     {
          id: 10,
          state: false,
          name: "Palanderska_gården",
          info: "Palanderska gården",
          disabled: false,
     },
     {
          id: 11,
          state: false,
          name: "Bostäder_och_Butiker-2",
          info: "Bostäder och butiker",
          disabled: false,
     },
     {
          id: 12,
          state: false,
          name: "Skolor",
          info: "Skolor kommer alltid att behövas och ingen anledning till att flytta dem heller. Skolorna kommer att bevaras och de kommer därför att byggas ut så att det får plats för fler personer.",
          disabled: false,
          hasPage: true,
          picture: "https://www.karlskrona.se/globalassets/skola-och-forskola/gymnasieskola/bilder/ehresvardska-gymnasiet.jpg?mode=page-intro-medium",
     },
     {
          id: 14,
          state: false,
          name: "Bostäder",
          info: "Bostäder",
          disabled: false,
     },
     {
          id: 15,
          state: false,
          name: "Bostäder-2",
          info: "Bostäder",
          disabled: false,
     },
     {
          id: 16,
          state: false,
          name: "Sparre_Lantmäteriet_Kulturområde",
          info: "Sparre Lantmäteriet Kulturområde",
          disabled: false,
     },
     {
          id: 17,
          state: false,
          name: "Bostäder_och_Butiker-3",
          info: "Bostäder och butiker",
          disabled: false,
     },
     {
          id: 18,
          state: false,
          name: "Butiker",
          info: "Butiker",
          disabled: false,
     },
     {
          id: 19,
          state: false,
          name: "Bostäder_och_Butiker",
          info: "Bostäder och butiker",
          disabled: false,
     },
     {
          id: 20,
          state: false,
          name: "Bostäder-3",
          info: "Bostäder",
          disabled: false,
     },
     {
          id: 21,
          state: false,
          name: "Bostäder-4",
          info: "Bostäder",
          disabled: false,
     },
     {
          id: 22,
          state: false,
          name: "Skolor-2",
          info: "Skolor",
          disabled: false,
     },
     {
          id: 23,
          state: false,
          name: "Bostäder-5",
          info: "Bostäder",
          disabled: false,
     },
     {
          id: 24,
          state: false,
          name: "Strandgården",
          info: "Strandgården har idag nyligen blivit byggt med en fin och intressant arkitektur. Något som saknas dock är ett parkeringshus som funkar för folk som bor där och folket som besöker. En gångbana längs vattnet, perfekt för att sola och fiska.",
          disabled: false,
     },
     {
          id: 25,
          state: false,
          name: "Möllebacken",
          info: "I nuläget så är Möllebacken en plats där många mindre lägenhetsbyggnader står bredvid varandra.          Planen är att i framtiden maximera platsen för att skapa större ihopkopplade hus där antalet boende också ökats. Möllebacken kommer då att utvidgas på höjden och nå upp till 8 våningar, detta leder också till flera bostäder med trevlig havsutsikt.",
          disabled: false,
          hasPage: true,
          picture: "https://tengbom.se/app/uploads/2016/05/ronnebygatan_07.RGB_color-600x600.jpg",
     },
     {
          id: 26,
          state: false,
          name: "Butiker-2",
          info: "Butiker",
          disabled: false,
     },
     {
          id: 27,
          state: false,
          name: "Stortorget",
          info: "Torget visar idag en lång historia om Karlskrona och så ska det vara i framtiden med. Det som kommer ändras på är fler lampor och mer historiska paneler och info-rutor belyses. Byggnaderna som Fredrikskyrkan, Tyska kyrkan och rådhuset står kvar. ",
          disabled: false,
          picture: "https://www.svenskakyrkan.se/bilder/563393/078.jpg?DoProcessing=&ci=0,0,1500,844&w=1680",
          hasPage: true,
     },
     {
          id: 28,
          state: false,
          name: "Hoglandspark",
          info: "Parken är en perfekt plats för utomhusaktiviteter och kulturell historia. Om man i framtiden väljer att avverka stora delar växtlighet så måste det finnas platser där man fortfarande kan besöka naturen, därför vill vi bevara den som den är i helhet men också öka växtligheten med fler träd, buskar och blommor.",
          disabled: false,
          picture: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/cb/a5/d1/20190520-180925-largejpg.jpg?w=1200&h=1200&s=1",
          hasPage: true,
     },
     {
          id: 29,
          state: false,
          name: "Amiralitetsparken",
          info: "Amiralitetsparken",
          disabled: false,
     },
     {
          id: 30,
          state: false,
          name: "Museum",
          info: "Blekinge Museum",
          disabled: false,
     },
     {
          id: 31,
          state: false,
          name: "Butiker-3",
          info: "Butiker",
          disabled: false,
     },
     {
          id: 32,
          state: false,
          name: "Bostäder_och_Butiker-4",
          info: "Bostäder och butiker",
          disabled: false,
     },
     {
          id: 33,
          state: false,
          name: "Brinova",
          info: "Brinova",
          disabled: false,
     },
     {
          id: 34,
          state: false,
          name: "Fisktorget",
          info: "Fisktorget",
          disabled: false,
     },
     {
          id: 35,
          state: false,
          name: "Varv_och_Marinbas",
          info: "Varv och Marinbas är tomt",
          disabled: true,
     },
     {
          id: 36,
          state: false,
          name: "Bröjkholmen",
          info: "Bröjkholmen",
          disabled: false,
     },
];

export default leds;
