name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'web/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'web/**'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./web/Dockerfile --tag trosso2122:$(date +%s)
