name: Build Web and Test Server
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: NPM install
        working-directory: ./web
        run: npm install
      - name: Build Web App
        working-directory: ./web
        run: CI=false npm run build
  deploy_web:
    runs-on: ubuntu-latest
     
    steps:
      - uses: actions/checkout@v3
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: NPM install
        working-directory: ./web
        run: npm install
      - name: Build Web App
        working-directory: ./web
        run: CI=false npm run deploy
  test_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: NPM install
        working-directory: ./server
        run: npm install
      - name: Test index.js
        working-directory: ./server
        run: npm run test
