# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Web and Test Server

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: NPM install
        working-directory: ./web
        run: npm install
      - name: Build Web App
        working-directory: ./web
        run: CI=false npm run build

  test_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: NPM install
        working-directory: ./server
        run: npm install
      - name: Test index.js
        working-directory: ./server
        run: npm run test
