name: Test Server
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: NPM install
        working-directory: ./server
        run: npm install
      - name: Test index.js
        working-directory: ./server
        run: npm run test
